services:
  mssql:
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - ${MSSQL_PORT}:1433
    image: mcr.microsoft.com/mssql/server:2022-latest 
    volumes:
      - ${MSSQL_DATA_DIR}:/var/opt/mssql