services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - ${PORT}:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}:/app/data
      - ${STACKS_DIR}:/opt/stacks
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
      - DOCKGE_ENABLE_CONSOLE=true
